version: "3"

services:
  postgres:
    image: postgres:17.0-alpine3.20
    container_name: finance-ai-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance-ai
    ports:
      - 5432:5432
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

volumes:
  .postgres-data:
